language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

install: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get -t ./...

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race ./...
  - go vet ./...
  - make build

deploy:
  skip_cleanup: true